adding adventure.txt file s
I got an error when trying "git push origin main"

To https://github.com/SWELIJ/git-branch-practice
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/SWELIJ/git-branch-practice'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

couldnt resolve